### ISSUE TITLE
when "." is used for a folder, the import is wrong

### ISSUE THREAD

**Issue by capaj** [eskimoblood/vscode-create-test#2]
I prefer to have my specs next to source files, so I set my path to spec as `.`

problem is I get wrong path when spec file is generated. it's missing `./` in the path at the beginning

**Comment by eskimoblood** [comment]
let me check

**Comment by eskimoblood** [comment]
Found it, still need to publish a new version. Will to it next week as I have no time right now

**Comment by eskimoblood** [comment]
took me a while but now it should be fixed
